# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170610_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_img',
            field=models.ImageField(default=None, upload_to='static/main/img/'),
        ),
        migrations.AlterField(
            model_name='artificialintellignece',
            name='letter',
            field=models.CharField(max_length=800),
        ),
    ]
