# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170610_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aim',
            old_name='caption_heder',
            new_name='caption_header',
        ),
    ]
