# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider_img',
            new_name='slider_image',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='slider_header',
            new_name='slider_text',
        ),
    ]
