# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_slider_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationsecurity',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informationsecurity',
            name='slide_image_1',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='informationsecurity',
            name='slide_image_2',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='informationsecurity',
            name='slide_image_3',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='webdeveloping',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webdeveloping',
            name='slide_image_1',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='webdeveloping',
            name='slide_image_2',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='webdeveloping',
            name='slide_image_3',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
