# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_aim_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
